# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- none

variables:
  imageRepo: helloworld
  tag: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build Stage
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: Docker@2
      inputs:
        containerRegistry: 'MyDockerHub'
        repository: 'bwce'
        command: 'build'
        Dockerfile: '**/Dockerfile'
    - task: PublishPipelineArtifact@1
      inputs:
        targetPath: '$(Pipeline.Workspace)'
        artifact: '$(imageRepo)'
        publishLocation: 'pipeline'
    - task: PublishPipelineArtifact@1
      inputs:
        targetPath: '$(Build.SourcesDirectory)/kubernetes'
        artifact: 'manifests'
        publishLocation: 'pipeline'
- stage: Deploy
  displayName: Deploy To AKS
  variables:
    dockersecret: akssecret
  dependsOn: Build
  jobs:
  - job:
    displayName: Deploy
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: DownloadPipelineArtifact@2
      inputs:
        buildType: 'current'
        artifactName: '$(imageRepo)'
        targetPath: '$(Pipeline.Workspace)'
    - task: DownloadPipelineArtifact@2
      inputs:
        buildType: 'current'
        artifactName: 'manifests'
        targetPath: '$(Pipeline.Workspace)' 
    - task: KubernetesManifest@0
      inputs:
        action: 'createSecret'
        kubernetesServiceConnection: 'MyTerraformAKSCluster'
        namespace: 'default'
        secretType: 'dockerRegistry'
        secretName: $(dockersecret)
        dockerRegistryEndpoint: 'MyDockerHub'
    
    - task: KubernetesManifest@0
      inputs:
        action: 'deploy'
        kubernetesServiceConnection: 'MyTerraformAKSCluster'
        namespace: 'default'
        manifests: '$(Pipeline.Workspace)/*.yml'
        containers: '$(imageRepo)'
        imagePullSecrets: '$(dockersecret)'


