trigger:
- none
stages:
- stage:
  displayName: Terraform Init

  jobs:
  - job: Initialisation
    displayName: Initialisation
    pool:
      vmimage: ubuntu-latest
    steps:
    - task: AzureCLI@2
      inputs:
        azureSubscription: 'MyAzureConnection'
        scriptType: 'bash'
        scriptLocation: 'inlineScript'
        inlineScript: 'terraform init'
      




